name: validation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  # Validate

  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Validate data
        uses: frictionlessdata/repository@v2
        with:
          packages: "datapackage.json"
